# Generated by Django 5.1.2 on 2024-10-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_option_1_question_option_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
