# Generated by Django 5.1.1 on 2025-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
