# Generated by Django 5.1.1 on 2025-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
