# Generated by Django 5.1.1 on 2025-05-07 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizationtest_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationtest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
