# Generated by Django 5.1.1 on 2025-06-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizationtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtestresult',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
