# Generated by Django 5.1.1 on 2025-05-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationtest_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtest',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationtest',
            name='total_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
