# Generated by Django 5.1.1 on 2025-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizationtestresult_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtest',
            name='test_code',
            field=models.CharField(max_length=20),
        ),
    ]
