# Generated by Django 5.1.1 on 2025-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizationtest_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
