# Generated by Django 5.1.1 on 2025-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtestresult',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testprogress',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
