# Generated by Django 5.1.1 on 2024-10-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_organizationadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('organization_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationadmin')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.subject')),
            ],
        ),
    ]
